CREATE TABLE LOGIN(UID INT AUTO_INCREMENT PRIMARY KEY,
MAIL_ID VARCHAR(30) NOT NULL UNIQUE,
PASSWORD VARCHAR (20) CHECK(LENGTH(PASSWORD)>6));

CREATE TABLE REGISTER(NAME VARCHAR (30) NOT NULL ,DEPARTMENT VARCHAR(20) NOT NULL,SALARY INT (10) NOT NULL,JOIN_DATE DATE NOT NULL);

ALTER TABLE REGISTER
ADD COLUMN UID INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE login
ADD CONSTRAINT FKEY
FOREIGN KEY (UID) REFERENCES register(UID);register

ALTER TABLE REGISTER
ADD COLUMN MAIL_ID VARCHAR(30) UNIQUE NOT NULL ;

ALTER TABLE register
ADD COLUMN PASSWORD VARCHAR(30) NOT NULL CHECK(LENGTH (PASSWORD)>6);